[terminal] Remove START_CWD from env
Otherwise, if someone starts another shell from this one, it will
inherit START_CWD and change to it, which may be unwanted behavior.

diff --git a/terminal/bashrc b/terminal/bashrc
--- a/terminal/bashrc
+++ b/terminal/bashrc
@@ -62,7 +62,8 @@ git_branch="$Bld$Pur\$(__git_ps1)$RCol"
 PS1="[$user_host \W$git_branch]\$ "
 
 if [ -n "$START_CWD" ]; then
-    cd "$START_CWD"
+    cd "$START_CWD" || echo "Failed to cd to $START_CWD"
+    unset START_CWD
 fi
 
 export REVIEW_BASE=master
